fix(download_models): Switch to TVM-RT
* With [0][1], the EdgeAI model_zoo & ti-tidl-osrt has now dropped Neo-AI-DLR
& switched to TVM-RT. Hence, update the download_models.sh to
switch to TVM-RT inorder to resolve following build errors observed in yocto

```
ERROR: edgeai-tidl-models-1.0-r0_edgeai_0 do_package: Fatal errors occurred in subprocesses:
Command '['aarch64-oe-linux-objcopy', '--only-keep-debug', '/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-SS-5710-deeplabv3lite-mobv2-cocoseg21-512x512/artifacts/deploy_lib.so.pc', '/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-SS-5710-deeplabv3lite-mobv2-cocoseg21-512x512/artifacts/.debug/deploy_lib.so.pc']' returned non-zero exit status 1.
Subprocess output:aarch64-oe-linux-objcopy: Unable to recognise the format of the input file `/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-SS-5710-deeplabv3lite-mobv2-cocoseg21-512x512/artifacts/deploy_lib.so.pc'
Command '['aarch64-oe-linux-objcopy', '--only-keep-debug', '/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-OD-5120-ssdLite-mobDet-DSP-coco-320x320/artifacts/deploy_lib.so.pc', '/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-OD-5120-ssdLite-mobDet-DSP-coco-320x320/artifacts/.debug/deploy_lib.so.pc']' returned non-zero exit status 1.
Subprocess output:aarch64-oe-linux-objcopy: Unable to recognise the format of the input file `/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-OD-5120-ssdLite-mobDet-DSP-coco-320x320/artifacts/deploy_lib.so.pc'
Command '['aarch64-oe-linux-objcopy', '--only-keep-debug', '/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-CL-3090-mobileNetV2-tv/artifacts/deploy_lib.so.pc', '/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-CL-3090-mobileNetV2-tv/artifacts/.debug/deploy_lib.so.pc']' returned non-zero exit status 1.
Subprocess output:aarch64-oe-linux-objcopy: Unable to recognise the format of the input file `/mnt/smpusdk-yocto-build/build/yocto-build_am62axx-evm/build/arago-tmp-default-glibc/work/aarch64-oe-linux/edgeai-tidl-models/1.0/package/opt/model_zoo/TVM-CL-3090-mobileNetV2-tv/artifacts/deploy_lib.so.pc'
```

[0] - https://software-dl.ti.com/jacinto7/esd/modelzoo/11_02_00/

[1] - https://git.ti.com/cgit/edgeai/meta-edgeai/commit/?h=scarthgap&id=1b88fbdf717da6f0c3ac1a6d7d4b23d2dff5f63d

Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>